language: node_js

node_js:
 - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database cosmos_authors_haven_test;' -U postgres

env:
  - NODE_ENV=test

cache:
 directories:
   - node_modules

script:
- npm test

after_success:
  - npm run coverage

deploy:
  provider: heroku
  app: author-haven-stage
  on:
    condition: $TRAVIS_BRANCH == develop
    repo: andela/cosmos-ah-backend
    branch: develop
  api_key:
    secure: $HEROKU_AUTH

deploy:
  provider: heroku
  app: author-haven
  on:
    condition: $TRAVIS_BRANCH == master
    repo: andela/cosmos-ah-backend
    branch: master
  api_key:
    secure: $HEROKU_AUTH
