

POST http://localhost:4000/api/v1/signup HTTP/1.1
content-Type: application/json

{
 "fullName" : "sulaiman Sanusi",
 "email": "sulaiman.sanusi@icloud.com",
 "password": "Secret@1234",
 "username": "ssanusi"
}
###
POST http://localhost:4000/api/v1/login HTTP/1.1
content-Type: application/json

{
 "email": "sulaiman.sanusi@icloud.com",
 "password": "Secret@1234"
}
###
PATCH http://localhost:4000/api/v1/comments/979eaa2e-5b8f-4103-8192-4639afae2bb9/like HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwYWE0NGIxLWZjNjktNDE1Yy05ZmYyLWU2MTZkN2Y4ZDFhNCIsImZ1bGxOYW1lIjoic3VsYWltYW4gU2FudXNpIiwiYmlvIjpudWxsLCJlbWFpbCI6InN1bGFpbWFuLnNhbnVzaUBpY2xvdWQuY29tIiwidXNlcm5hbWUiOiJzc2FudXNpIiwicm9sZSI6ImF1dGhvciIsImlhdCI6MTU1NjE5MDQ3NCwiZXhwIjoxNTU2Mjc2ODc0fQ.f3IIMDrIE01PId9SzrYicKWkdKPKNebtzD2q6H_87pY

